name: 'Run tests on NodeJS'

on:
  push:
    branches:
      [main]
  workflow_dispatch:

jobs:
  default:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5

      - name: Lint with .editorconfig
        run: npx @biomejs/biome ci --config-path biome.editorconfig.json
        continue-on-error: true

      - name: Lint without .editorconfig
        run: |
          rm .editorconfig
          npx @biomejs/biome ci --config-path biome.no-editorconfig.json
